name:                 eclaire
version:              0.1.0.0
visibility:           public
id:                   eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH
key:                  eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH
license:              MIT AND Zlib
maintainer:           Eclaire contributors
author:               Eclaire contributors
synopsis:             Cross-language semantic UI layout engine powered by Clay
category:             UI
abi:                  033c218c387d831bb1276552dd5b2252
exposed:              True
exposed-modules:      Eclaire
import-dirs:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/lib/aarch64-osx-ghc-9.10.2-b8ed/eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH

library-dirs:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/lib/aarch64-osx-ghc-9.10.2-b8ed/eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH

library-dirs-static:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/lib/aarch64-osx-ghc-9.10.2-b8ed/eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH

dynamic-library-dirs:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/lib/aarch64-osx-ghc-9.10.2-b8ed

data-dir:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/share/aarch64-osx-ghc-9.10.2-b8ed/eclaire-0.1.0.0

hs-libraries:         HSeclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH
include-dirs:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/lib/aarch64-osx-ghc-9.10.2-b8ed/eclaire-0.1.0.0-GacctLVVX0OFiAATOHKiZH/include

depends:              base-4.20.1.0-7c8f
haddock-interfaces:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/doc/eclaire-0.1.0.0/eclaire.haddock

haddock-html:
    /Users/mattlaine/para/projects/layouts/eclaire/.stack-work/install/aarch64-osx/da3b69980b476f78383aa5124a67e6097c553cc47d0b7e3790ab8a173f859a2f/9.10.2/doc/eclaire-0.1.0.0
