#define CLAY_IMPLEMENTATION
#include "clay.h"
#include "eclaire.h"
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

typedef struct { void *memory; size_t memory_size; uint32_t max_elements; EclaireElement *elements; uint32_t count; uint32_t depth; EclaireMeasureTextFn measure; void *measure_data; EclaireErrorFn error; void *error_data; uint32_t last_error; Clay_RenderCommandArray commands; int initialized,frame; } EclaireState;
static EclaireState s;
static void clay_error(Clay_ErrorData d) { s.last_error=(uint32_t)d.errorType+1u; if(s.error)s.error(s.last_error,d.errorText.chars,s.error_data); }
static Clay_Dimensions measure_text(Clay_StringSlice text,Clay_TextElementConfig *cfg,void *ud) { (void)ud; Clay_Dimensions d={0}; if(s.measure){ char *z=(char*)malloc((size_t)text.length+1); if(z){memcpy(z,text.chars,(size_t)text.length);z[text.length]=0;d.width=s.measure(z,cfg->fontSize,s.measure_data);free(z);} } else { d.width=(float)text.length*(float)cfg->fontSize*.55f; } d.height=cfg->fontSize?cfg->fontSize:16; return d; }
uint32_t eclaire_ir_version(void){return ECLAIRE_IR_VERSION;}
size_t eclaire_min_memory_size(uint32_t max_elements){if(!max_elements||max_elements>65535)return 0;Clay_SetMaxElementCount((int32_t)max_elements);Clay_SetMaxMeasureTextCacheWordCount((int32_t)(max_elements*32));return (size_t)Clay_MinMemorySize();}
EclaireStatus eclaire_init(void *memory,size_t memory_size,uint32_t max_elements,float width,float height,EclaireMeasureTextFn measure,void *measure_data,EclaireErrorFn error,void *error_data){if(!memory||!max_elements||max_elements>65535)return ECLAIRE_ERR_ARGUMENT;Clay_SetMaxElementCount((int32_t)max_elements);Clay_SetMaxMeasureTextCacheWordCount((int32_t)(max_elements*32));if(memory_size<Clay_MinMemorySize())return ECLAIRE_ERR_ARGUMENT;memset(&s,0,sizeof(s));s.memory=memory;s.memory_size=memory_size;s.max_elements=max_elements;s.measure=measure;s.measure_data=measure_data;s.error=error;s.error_data=error_data;s.elements=calloc(max_elements,sizeof(EclaireElement));if(!s.elements)return ECLAIRE_ERR_CAPACITY;Clay_Arena a=Clay_CreateArenaWithCapacityAndMemory(memory_size,memory);Clay_ErrorHandler eh={.errorHandlerFunction=clay_error};Clay_Initialize(a,(Clay_Dimensions){width,height},eh);Clay_SetMeasureTextFunction(measure_text,NULL);s.initialized=1;return ECLAIRE_OK;}
static Clay_SizingAxis sizing(float n,uint8_t mode){switch(mode){case ECLAIRE_FIXED:return CLAY_SIZING_FIXED(n);case ECLAIRE_FIT:return CLAY_SIZING_FIT(0);default:return CLAY_SIZING_GROW(0);}}
EclaireStatus eclaire_begin_frame(float width,float height,float px,float py,int down){if(!s.initialized)return ECLAIRE_ERR_STATE;s.count=s.depth=0;s.last_error=0;s.frame=1;Clay_SetLayoutDimensions((Clay_Dimensions){width,height});Clay_SetPointerState((Clay_Vector2){px,py},down!=0);Clay_BeginLayout();return ECLAIRE_OK;}
EclaireStatus eclaire_push_element(const EclaireElement *e){if(!s.frame||!e)return ECLAIRE_ERR_STATE;if(s.count>=s.max_elements)return ECLAIRE_ERR_CAPACITY;if(s.depth>=256)return ECLAIRE_ERR_CAPACITY;uint32_t i=s.count++;s.elements[i]=*e;s.depth++;Clay_ElementId id={.id=(uint32_t)(e->stable_id^(e->stable_id>>32))};Clay_SizingAxis wx=sizing(e->width,e->sizing),hy=sizing(e->height,e->sizing);Clay_LayoutConfig l=CLAY__INIT(Clay_LayoutConfig){.sizing={.width=wx,.height=hy},.padding={(uint16_t)e->padding,(uint16_t)e->padding,(uint16_t)e->padding,(uint16_t)e->padding},.childGap=(uint16_t)e->gap,.layoutDirection=e->direction==ECLAIRE_ROW?CLAY_LEFT_TO_RIGHT:CLAY_TOP_TO_BOTTOM};Clay_ElementDeclaration d=CLAY__INIT(Clay_ElementDeclaration){.layout=l};Clay__OpenElementWithId(id);Clay__ConfigureOpenElement(d);if(e->kind==ECLAIRE_TEXT&&e->text){EclaireStatus st=eclaire_push_text(e->stable_id,e->text,(uint16_t)(e->font_size>0?e->font_size:16),0xffffffffu);if(st!=ECLAIRE_OK)return st;}return ECLAIRE_OK;}
EclaireStatus eclaire_pop_element(void){if(!s.frame||!s.depth)return ECLAIRE_ERR_STATE;Clay__CloseElement();s.depth--;return ECLAIRE_OK;}
EclaireStatus eclaire_push_text(uint64_t id,const char *text,uint16_t font,uint32_t rgba){if(!s.frame||!text)return ECLAIRE_ERR_STATE;Clay_String cs={.isStaticallyAllocated=false,.length=(int32_t)strlen(text),.chars=text};Clay_Color c={(float)((rgba>>24)&255),(float)((rgba>>16)&255),(float)((rgba>>8)&255),(float)(rgba&255)};Clay__OpenTextElement(cs,CLAY__INIT(Clay_TextElementConfig){.fontSize=font,.textColor=c});(void)id;return ECLAIRE_OK;}
EclaireStatus eclaire_end_frame(float dt){if(!s.frame||s.depth)return ECLAIRE_ERR_STATE;s.commands=Clay_EndLayout(dt);s.frame=0;return s.last_error?ECLAIRE_ERR_CLAY:ECLAIRE_OK;}
uint32_t eclaire_render_command_count(void){return (uint32_t)s.commands.length;}
int eclaire_render_command(uint32_t i,uint32_t *kind,EclaireRect *r,uint32_t *rgba,const char **text){Clay_RenderCommand *c=Clay_RenderCommandArray_Get(&s.commands,(int32_t)i);if(!c)return 0;if(kind)*kind=(uint32_t)c->commandType;if(r)*r=(EclaireRect){c->boundingBox.x,c->boundingBox.y,c->boundingBox.width,c->boundingBox.height};if(rgba)*rgba=0;if(text)*text=NULL;if(c->commandType==CLAY_RENDER_COMMAND_TYPE_TEXT){if(rgba){Clay_Color x=c->renderData.text.textColor;*rgba=((uint32_t)(uint8_t)x.r<<24)|((uint32_t)(uint8_t)x.g<<16)|((uint32_t)(uint8_t)x.b<<8)|(uint8_t)x.a;}if(text)*text=c->renderData.text.stringContents.chars;}return 1;}
int eclaire_get_element_rect(uint64_t id,EclaireRect *r){if(!r)return 0;Clay_ElementId x={.id=(uint32_t)(id^(id>>32))};Clay_ElementData d=Clay_GetElementData(x);if(!d.found)return 0;*r=(EclaireRect){d.boundingBox.x,d.boundingBox.y,d.boundingBox.width,d.boundingBox.height};return 1;}
uint32_t eclaire_last_error(void){return s.last_error;}
